Fix reason code parsing
Sometimes the reason text contains more than one opening parenthesis
(e.g. "Sick leave (1-3 days)(SAP)") and this unpacking code would then
yield an error like this:

    ValueError: too many values to unpack (expected 2)

Fix this error by using "rsplit" with additional argument "1" so that
only the last opening parenthesis is used to split the reason text to
description and code.